// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/detail-local': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/detail-local').default>>>>
    }
    '/api/details': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/details').default>>>>
    }
    '/api/local': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/local').default>>>>
    }
    '/api/locations-local': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/locations-local').default>>>>
    }
    '/api/locations': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/locations').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}